# Generated by Django 5.2.15 on 2026-06-26 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('created_by_user_id', models.CharField(max_length=128)),
                ('direct_pair_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'messenger_rooms',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['room_type', '-updated_at'], name='room_type_updated_idx'), models.Index(fields=['created_by_user_id'], name='room_creator_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('direct_pair_key__isnull', False), ('room_type', 'direct')), models.Q(('direct_pair_key__isnull', True), ('room_type', 'group')), _connector='OR'), name='room_pair_key_by_type')],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('added_by_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rooms.room')),
            ],
            options={
                'db_table': 'messenger_room_members',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['room', 'is_active'], name='member_room_active_idx'), models.Index(fields=['user_id', 'is_active'], name='member_user_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'user_id'), name='unique_room_user')],
            },
        ),
    ]
