# Generated by Django 5.2.15 on 2026-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommember_group_lifecycle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='roommember',
            index=models.Index(fields=['room', 'is_active', 'joined_at', 'id'], name='member_room_active_join_idx'),
        ),
    ]
