from django.conf import settings
from rest_framework import serializers

class EncryptedAttachmentInitiateSerializer(serializers.Serializer):
    device_id = serializers.UUIDField()
    storage_provider = serializers.ChoiceField(
        choices=[
            "cloudinary",
            "s3",
            "local",
        ],
        required=False,
        default="cloudinary",
    )
    storage_key = serializers.CharField(
        required=False,
        allow_blank=True,
        max_length=512,
        trim_whitespace=True,
    )
    media_category = serializers.ChoiceField(
        choices=[
            "image",
            "video",
            "audio",
            "file",
        ],
        required=False,
        default="file",
    )
    expires_at = serializers.DateTimeField(
        required=False,
        allow_null=True,
    )

class CloudinarySignedUploadSerializer(serializers.Serializer):
    FORBIDDEN_TOP_LEVEL_FIELDS = {
        "storage_key",
        "folder",
        "public_id",
        "resource_type",
        "cloud_name",
        "api_key",
        "api_secret",
        "signature",
        "filename",
        "file_name",
        "mime_type",
        "content_type",
        "caption",
        "thumbnail",
        "thumbnail_url",
        "dimensions",
        "width",
        "height",
        "plaintext",
        "secret",
        "key",
        "attachment_key",
        "raw_key",
        "decryption_key",
    }

    device_id = serializers.UUIDField()

    media_category = serializers.ChoiceField(
        choices=[
            "image",
            "video",
            "audio",
            "file",
        ],
        required=False,
        default="file",
    )

    ciphertext_size_hint = serializers.IntegerField(
        min_value=1,
        max_value=settings.ATTACHMENT_MAX_CIPHERTEXT_BYTES,
    )

    expires_in_seconds = serializers.IntegerField(
        required=False,
        default=settings.ATTACHMENT_UPLOAD_SIGNATURE_TTL_SECONDS,
        min_value=settings.ATTACHMENT_MIN_TTL_SECONDS,
        max_value=settings.ATTACHMENT_UPLOAD_MAX_TTL_SECONDS,
    )

    def to_internal_value(self, data):
        forbidden_fields = sorted(
            field
            for field in self.FORBIDDEN_TOP_LEVEL_FIELDS
            if field in data
        )

        if forbidden_fields:
            raise serializers.ValidationError(
                {
                    field: [
                        "This field is not accepted by the backend. "
                        "Encrypted attachment metadata must stay inside "
                        "encrypted_payload, and Cloudinary destination/signature "
                        "fields are generated by the backend."
                    ]
                    for field in forbidden_fields
                }
            )

        return super().to_internal_value(data)
    




class EncryptedAttachmentCompleteSerializer(serializers.Serializer):
    device_id = serializers.UUIDField()
    ciphertext_sha256 = serializers.CharField(
        max_length=64,
        min_length=64,
        trim_whitespace=True,
    )
    ciphertext_size = serializers.IntegerField(
        min_value=1,
        max_value=settings.ATTACHMENT_MAX_CIPHERTEXT_BYTES,
    )
    def validate_ciphertext_sha256(self, value):
        normalized = value.strip().lower()

        if any(character not in "0123456789abcdef" for character in normalized):
            raise serializers.ValidationError(
                "ciphertext_sha256 must be a hex SHA-256 digest."
            )

        return normalized


class EncryptedAttachmentDeleteSerializer(serializers.Serializer):
    device_id = serializers.UUIDField()


class EncryptedAttachmentSerializer(serializers.Serializer):
    id = serializers.UUIDField(read_only=True)
    uploader_user_id = serializers.CharField(read_only=True)
    uploader_device_id = serializers.SerializerMethodField()
    storage_provider = serializers.CharField(read_only=True)
    storage_key = serializers.CharField(read_only=True)
    ciphertext_sha256 = serializers.CharField(read_only=True)
    ciphertext_size = serializers.IntegerField(read_only=True)
    media_category = serializers.CharField(read_only=True)
    upload_status = serializers.CharField(read_only=True)
    created_at = serializers.DateTimeField(read_only=True)
    completed_at = serializers.DateTimeField(read_only=True)
    expires_at = serializers.DateTimeField(read_only=True)

    def get_uploader_device_id(self, instance):
        return instance.uploader_device_id