import uuid

from apps.e2ee_devices.models import Device
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q

from apps.rooms.models import (
    EXTERNAL_USER_ID_MAX_LENGTH,
    Room,
)


class Message(models.Model):
    """
    Stores encrypted messages for both direct and group rooms.

    The messenger service stores ciphertext only. Message encryption and
    decryption must happen on user devices.

    The same table is used for:
    - Direct-room messages
    - Group-room messages
    - Text messages
    - Encrypted attachment messages
    - Encrypted location or contact messages
    """

    class MessageType(models.TextChoices):
        TEXT = "text", "Text"
        IMAGE = "image", "Image"
        VIDEO = "video", "Video"
        AUDIO = "audio", "Audio"
        FILE = "file", "File"
        LOCATION = "location", "Location"
        CONTACT = "contact", "Contact"
        EDIT = "edit", "Edit"
        DELETE = "delete", "Delete"
        REACTION = "reaction", "Reaction"
        SYSTEM = "system", "System"
        

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    room = models.ForeignKey(
        Room,
        on_delete=models.PROTECT,
        related_name="messages",
    )

    sender_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    # Identifies the sender's device. This becomes important when a user
    # signs in on multiple devices with different encryption sessions.
    sender_device_id = models.CharField(
        max_length=128,
    )

    # Generated by the sender's device before sending the message.
    #
    # Together with sender_user_id, this provides idempotency. Retrying the
    # same HTTP request will not create the same message twice.
    client_message_id = models.UUIDField()

    # This is broad server-visible metadata. The actual message content,
    # filename, caption, coordinates, or contact data must remain inside
    # encrypted_payload.
    message_type = models.CharField(
        max_length=20,
        choices=MessageType.choices,
        default=MessageType.TEXT,
    )

    # Base64-encoded ciphertext or an encrypted serialized envelope.
    #
    # This field must never contain plaintext.
    encrypted_payload = models.TextField()

    # Non-secret cryptographic metadata required by the recipient client.
    #
    # Examples:
    # {
    #     "algorithm": "xchacha20-poly1305",
    #     "nonce": "base64-value",
    #     "key_id": "sender-key-id",
    #     "protocol_version": 1
    # }
    #
    # Never store private keys or raw symmetric message keys here.
    encryption_metadata = models.JSONField(
        default=dict,
        blank=True,
    )

    # Allows the application to upgrade the encrypted payload format while
    # retaining compatibility with older messages.
    encryption_version = models.PositiveSmallIntegerField(
        default=1,
    )

    # Optional reply relationship. Both messages must belong to the same
    # room. The replied-to message content remains encrypted.
    reply_to = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        related_name="replies",
        null=True,
        blank=True,
    )

    # Time generated by the sending device. It is informational and should
    # not be trusted for authorization or strict server ordering.
    client_sent_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    # Trusted server receipt time.
    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        db_table = "messenger_messages"

        ordering = [
            "created_at",
            "id",
        ]

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "sender_user_id",
                    "client_message_id",
                ],
                name="unique_sender_client_msg",
            ),
        ]

        indexes = [
            models.Index(
                fields=[
                    "room",
                    "created_at",
                ],
                name="msg_room_created_idx",
            ),
            models.Index(
                fields=[
                    "sender_user_id",
                    "created_at",
                ],
                name="msg_sender_created_idx",
            ),
            models.Index(
                fields=[
                    "room",
                    "message_type",
                    "created_at",
                ],
                name="msg_room_type_time_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"{self.message_type} message "
            f"{self.id} in room {self.room_id}"
        )

    def clean(self) -> None:
        super().clean()

        self.sender_user_id = self.sender_user_id.strip()
        self.sender_device_id = self.sender_device_id.strip()
        self.encrypted_payload = self.encrypted_payload.strip()

        errors = {}

        if not self.sender_user_id:
            errors["sender_user_id"] = (
                "The sender user ID is required."
            )

        if not self.sender_device_id:
            errors["sender_device_id"] = (
                "The sender device ID is required."
            )

        if not self.encrypted_payload:
            errors["encrypted_payload"] = (
                "An encrypted payload is required."
            )

        if not isinstance(self.encryption_metadata, dict):
            errors["encryption_metadata"] = (
                "Encryption metadata must be a JSON object."
            )

        if self.encryption_version < 1:
            errors["encryption_version"] = (
                "Encryption version must be at least 1."
            )

        if self.reply_to_id:
            if self.reply_to_id == self.id:
                errors["reply_to"] = (
                    "A message cannot reply to itself."
                )

            elif (
                self.reply_to is not None
                and self.reply_to.room_id != self.room_id
            ):
                errors["reply_to"] = (
                    "A reply and its original message must belong "
                    "to the same room."
                )

        if errors:
            raise ValidationError(errors)
        

class MessageReceipt(models.Model):
    """
    Device-level delivered/read tracking for encrypted messages.

    The server stores only receipt state. It never stores plaintext message
    content, decrypted content, or cryptographic keys.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="receipts",
    )

    recipient_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    recipient_device = models.ForeignKey(
        Device,
        on_delete=models.PROTECT,
        related_name="message_receipts",
        null=True,
        blank=True,
    )

    delivered_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    read_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        db_table = "messenger_message_receipts"
        ordering = [
            "message",
            "recipient_user_id",
            "recipient_device",
        ]
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "message",
                    "recipient_user_id",
                    "recipient_device",
                ],
                name="uniq_msg_receipt_device",
            ),
        ]
        indexes = [
            models.Index(
                fields=[
                    "message",
                    "recipient_user_id",
                ],
                name="receipt_msg_user_idx",
            ),
            models.Index(
                fields=[
                    "recipient_user_id",
                    "updated_at",
                ],
                name="receipt_user_updated_idx",
            ),
            models.Index(
                fields=[
                    "recipient_device",
                    "updated_at",
                ],
                name="receipt_device_updated_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"Receipt(message={self.message_id}, "
            f"user={self.recipient_user_id}, "
            f"device={self.recipient_device_id})"
        )

    def clean(self) -> None:
        super().clean()

        self.recipient_user_id = self.recipient_user_id.strip()

        errors = {}

        if not self.recipient_user_id:
            errors["recipient_user_id"] = (
                "The recipient user ID is required."
            )

        if self.recipient_device_id:
            device_user_id = str(
                self.recipient_device.user_id
            ).strip()

            if device_user_id != self.recipient_user_id:
                errors["recipient_device"] = (
                    "The recipient device must belong to the "
                    "recipient user."
                )

        if self.read_at and self.delivered_at is None:
            self.delivered_at = self.read_at

        if (
            self.read_at
            and self.delivered_at
            and self.read_at < self.delivered_at
        ):
            errors["read_at"] = (
                "Read time cannot be earlier than delivered time."
            )

        if errors:
            raise ValidationError(errors)


class EncryptedAttachment(models.Model):
    """
    Server-visible metadata for an encrypted attachment.

    The client encrypts the file before upload. The plaintext filename,
    exact MIME type, caption, and attachment decryption key should live
    inside encrypted message plaintext when privacy requires it.
    """

    class StorageProvider(models.TextChoices):
        CLOUDINARY = "cloudinary", "Cloudinary"
        S3 = "s3", "S3"
        LOCAL = "local", "Local"

    class MediaCategory(models.TextChoices):
        IMAGE = "image", "Image"
        VIDEO = "video", "Video"
        AUDIO = "audio", "Audio"
        FILE = "file", "File"

    class UploadStatus(models.TextChoices):
        INITIATED = "initiated", "Initiated"
        COMPLETED = "completed", "Completed"
        DELETED = "deleted", "Deleted"
        EXPIRED = "expired", "Expired"

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    uploader_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    uploader_device = models.ForeignKey(
        Device,
        on_delete=models.PROTECT,
        related_name="encrypted_attachments",
    )

    storage_provider = models.CharField(
        max_length=40,
        choices=StorageProvider.choices,
        default=StorageProvider.CLOUDINARY,
    )

    storage_key = models.CharField(
        max_length=512,
        unique=True,
    )

    ciphertext_sha256 = models.CharField(
        max_length=64,
        blank=True,
        default="",
    )

    ciphertext_size = models.PositiveBigIntegerField(
        default=0,
    )

    media_category = models.CharField(
        max_length=20,
        choices=MediaCategory.choices,
        default=MediaCategory.FILE,
    )

    upload_status = models.CharField(
        max_length=20,
        choices=UploadStatus.choices,
        default=UploadStatus.INITIATED,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    completed_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    expires_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    class Meta:
        db_table = "messenger_encrypted_attachments"
        ordering = [
            "-created_at",
            "-id",
        ]
        constraints = [
            models.CheckConstraint(
                condition=Q(ciphertext_size__gte=0),
                name="attachment_ciphertext_size_gte_0",
            ),
        ]
        indexes = [
            models.Index(
                fields=[
                    "uploader_user_id",
                    "-created_at",
                ],
                name="attach_uploader_time_idx",
            ),
            models.Index(
                fields=[
                    "uploader_device",
                    "-created_at",
                ],
                name="attach_device_time_idx",
            ),
            models.Index(
                fields=[
                    "upload_status",
                    "-created_at",
                ],
                name="attach_status_time_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"EncryptedAttachment(id={self.id}, "
            f"status={self.upload_status})"
        )

    def clean(self) -> None:
        super().clean()

        self.uploader_user_id = self.uploader_user_id.strip()
        self.storage_key = self.storage_key.strip()
        self.ciphertext_sha256 = self.ciphertext_sha256.strip().lower()

        errors = {}

        if not self.uploader_user_id:
            errors["uploader_user_id"] = (
                "Uploader user ID is required."
            )

        if self.uploader_device_id:
            device_user_id = str(
                self.uploader_device.user_id
            ).strip()

            if device_user_id != self.uploader_user_id:
                errors["uploader_device"] = (
                    "Uploader device must belong to the uploader user."
                )

        if not self.storage_key:
            errors["storage_key"] = "Storage key is required."

        forbidden_storage_fragments = (
            "plaintext",
            "private",
            "secret",
            "raw_key",
            "attachment_key",
        )

        normalized_storage_key = self.storage_key.lower()

        if any(
            fragment in normalized_storage_key
            for fragment in forbidden_storage_fragments
        ):
            errors["storage_key"] = (
                "Storage key must not contain plaintext or secret "
                "attachment-key material."
            )

        if self.ciphertext_sha256:
            is_valid_sha = (
                len(self.ciphertext_sha256) == 64
                and all(
                    character in "0123456789abcdef"
                    for character in self.ciphertext_sha256
                )
            )

            if not is_valid_sha:
                errors["ciphertext_sha256"] = (
                    "Ciphertext SHA-256 must be a 64-character hex digest."
                )

        if (
            self.upload_status == self.UploadStatus.COMPLETED
            and not self.completed_at
        ):
            errors["completed_at"] = (
                "Completed attachments require completed_at."
            )

        if errors:
            raise ValidationError(errors)



class MessageKeyEnvelope(models.Model):
    """
    An encrypted copy of a message's content-encryption key for one device.

    The message ciphertext remains stored once in the Message table.
    Each authorized device receives a separately encrypted copy of the
    message key through this model.

    No plaintext message key or private key is stored by the server.
    """

    class Protocol(models.TextChoices):
        DOUBLE_RATCHET = (
            "double_ratchet",
            "Double Ratchet",
        )
        GROUP_SENDER_KEY = (
            "group_sender_key",
            "Group Sender Key",
        )
        DEVICE_SYNC = (
            "device_sync",
            "Device Synchronization",
        )

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="key_envelopes",
    )

    recipient_user_id = models.CharField(
        max_length=128,
    )

    recipient_device = models.ForeignKey(
        Device,
        on_delete=models.PROTECT,
        related_name="message_key_envelopes",
    )

    protocol = models.CharField(
        max_length=30,
        choices=Protocol.choices,
        default=Protocol.DOUBLE_RATCHET,
    )

    # Opaque client-generated session identifier. It must not contain
    # session secrets or private keys.
    session_reference = models.CharField(
        max_length=128,
        blank=True,
        default="",
    )

    # Base64-encoded encrypted/wrapped message content key.
    wrapped_message_key = models.TextField()

    # Public protocol information required by the recipient client.
    # Examples:
    # {
    #     "ratchet_public_key": "...",
    #     "message_number": 15,
    #     "previous_chain_length": 4,
    #     "nonce": "...",
    #     "algorithm": "xchacha20poly1305"
    # }
    #
    # This must never contain private keys or plaintext message keys.
    key_wrap_metadata = models.JSONField(
        default=dict,
    )

    envelope_version = models.PositiveSmallIntegerField(
        default=1,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        db_table = "messenger_message_key_envelopes"

        ordering = [
            "created_at",
            "id",
        ]

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "message",
                    "recipient_device",
                ],
                name="unique_message_device_envelope",
            ),
        ]

        indexes = [
            models.Index(
                fields=[
                    "message",
                    "recipient_user_id",
                ],
                name="envelope_message_user_idx",
            ),
            models.Index(
                fields=[
                    "recipient_device",
                    "created_at",
                ],
                name="envelope_device_time_idx",
            ),
            models.Index(
                fields=[
                    "recipient_user_id",
                    "created_at",
                ],
                name="envelope_user_time_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"Message {self.message_id} envelope for "
            f"device {self.recipient_device_id}"
        )

    def clean(self) -> None:
        super().clean()

        self.recipient_user_id = (
            self.recipient_user_id.strip()
        )
        self.session_reference = (
            self.session_reference.strip()
        )
        self.wrapped_message_key = (
            self.wrapped_message_key.strip()
        )

        errors = {}

        if not self.recipient_user_id:
            errors["recipient_user_id"] = (
                "The recipient user ID is required."
            )

        if not self.wrapped_message_key:
            errors["wrapped_message_key"] = (
                "The encrypted message key is required."
            )

        if not isinstance(
            self.key_wrap_metadata,
            dict,
        ):
            errors["key_wrap_metadata"] = (
                "Key-wrap metadata must be a JSON object."
            )

        if self.envelope_version < 1:
            errors["envelope_version"] = (
                "The envelope version must be at least 1."
            )

        if self.recipient_device_id:
            device_user_id = str(
                self.recipient_device.user_id
            ).strip()

            if (
                self.recipient_user_id
                and device_user_id
                != self.recipient_user_id
            ):
                errors["recipient_user_id"] = (
                    "The recipient user ID does not own the "
                    "selected recipient device."
                )

        if errors:
            raise ValidationError(errors)


class MessageRecoveryEnvelope(models.Model):
    """
    Stores a message content key wrapped for one user's recovery key.

    This is separate from MessageKeyEnvelope because recovery is
    user-level while normal delivery envelopes are device-level.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        related_name="recovery_envelopes",
    )

    # External Identity-service user ID.
    recovery_owner_user_id = models.CharField(
        max_length=128,
    )

    # Version of the user's RecoveryBundle public key that wrapped
    # this message content key.
    recovery_key_version = models.PositiveSmallIntegerField()

    wrapped_message_key = models.TextField()

    key_wrap_metadata = models.JSONField(
        default=dict,
    )

    envelope_version = models.PositiveSmallIntegerField(
        default=1,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        db_table = "messenger_message_recovery_envelopes"

        constraints = [
            models.UniqueConstraint(
                fields=[
                    "message",
                    "recovery_owner_user_id",
                ],
                name="unique_message_recovery_owner",
            ),
            models.CheckConstraint(
                condition=Q(
                    recovery_key_version__gte=1,
                ),
                name="recovery_key_version_gte_1",
            ),
            models.CheckConstraint(
                condition=Q(
                    envelope_version__gte=1,
                ),
                name="recovery_envelope_version_gte_1",
            ),
        ]

        indexes = [
            models.Index(
                fields=[
                    "recovery_owner_user_id",
                    "-created_at",
                ],
                name="recovery_owner_time_idx",
            ),
            models.Index(
                fields=[
                    "message",
                    "recovery_owner_user_id",
                ],
                name="recovery_message_owner_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"MessageRecoveryEnvelope("
            f"message={self.message_id}, "
            f"owner={self.recovery_owner_user_id}, "
            f"key_version={self.recovery_key_version}"
            f")"
        )



class GroupMessageEncryption(models.Model):
    """Group-message sender-key encryption metadata.

    The ciphertext itself stays in Message.encrypted_payload.
    This model stores only public routing/verification metadata needed for
    group sender-key decryption. It must never store plaintext, message keys,
    sender-chain secrets, private signing keys, recovery secrets, or ratchet
    state.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    message = models.OneToOneField(
        Message,
        on_delete=models.CASCADE,
        related_name="group_encryption",
    )

    group_room = models.ForeignKey(
        "rooms.Room",
        on_delete=models.CASCADE,
        related_name="group_message_encryptions",
    )

    epoch = models.ForeignKey(
        "group_chat.GroupEncryptionEpoch",
        on_delete=models.PROTECT,
        related_name="group_message_encryptions",
    )

    sender_key = models.ForeignKey(
        "group_chat.GroupSenderKey",
        on_delete=models.PROTECT,
        related_name="group_message_encryptions",
    )

    chain_iteration = models.PositiveIntegerField()

    signature = models.TextField()

    encryption_metadata = models.JSONField(
        default=dict,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        db_table = "messenger_group_message_encryptions"
        ordering = [
            "-created_at",
            "-id",
        ]
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "sender_key",
                    "chain_iteration",
                ],
                name="uniq_group_sender_iter",
            ),
            models.CheckConstraint(
                check=models.Q(chain_iteration__gte=0),
                name="group_msg_iter_gte_0",
            ),
        ]
        indexes = [
            models.Index(
                fields=[
                    "group_room",
                    "epoch",
                    "-created_at",
                ],
                name="gmenc_room_epoch_idx",
            ),
            models.Index(
                fields=[
                    "sender_key",
                    "chain_iteration",
                ],
                name="gmenc_sender_iter_idx",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"Group message {self.message_id} "
            f"epoch={self.epoch_id} iteration={self.chain_iteration}"
        )

    def clean(self) -> None:
        super().clean()

        self.signature = self.signature.strip()

        errors = {}

        if not self.signature:
            errors["signature"] = "Group message signature is required."

        if not isinstance(self.encryption_metadata, dict):
            errors["encryption_metadata"] = (
                "Encryption metadata must be a JSON object."
            )

        if self.message_id and self.group_room_id:
            if self.message.room_id != self.group_room_id:
                errors["message"] = (
                    "Message room must match group encryption room."
                )

        if self.group_room_id:
            if self.group_room.room_type != "group":
                errors["group_room"] = (
                    "Group message encryption can only attach to group rooms."
                )

        if self.epoch_id and self.group_room_id:
            if self.epoch.group_room_id != self.group_room_id:
                errors["epoch"] = "Epoch does not belong to this group."

        if self.sender_key_id and self.group_room_id:
            if self.sender_key.group_room_id != self.group_room_id:
                errors["sender_key"] = (
                    "Sender key does not belong to this group."
                )

        if self.sender_key_id and self.epoch_id:
            if self.sender_key.epoch_id != self.epoch_id:
                errors["sender_key"] = (
                    "Sender key does not belong to this epoch."
                )

        if self.message_id and self.sender_key_id:
            if self.message.sender_user_id != self.sender_key.sender_user_id:
                errors["message"] = (
                    "Message sender must match sender-key owner."
                )

            if (
                str(self.message.sender_device_id)
                != str(self.sender_key.sender_device_id)
            ):
                errors["message"] = (
                    "Message sender device must match sender-key device."
                )

        forbidden_words = (
            "plaintext",
            "private_key",
            "secret",
            "sender_chain_secret",
            "message_key",
            "ratchet",
            "recovery_key",
        )

        for key in self.encryption_metadata.keys():
            normalized_key = str(key).lower()
            if any(word in normalized_key for word in forbidden_words):
                errors["encryption_metadata"] = (
                    "Encryption metadata must not contain plaintext or "
                    "secret cryptographic material."
                )
                break

        if errors:
            raise ValidationError(errors)



class ContactDeliveryPolicy(models.Model):
    """
    Messenger-local read projection of identity contact delivery policy.

    Identity is the source of truth. Messenger only reads this table during
    message send, so direct-message delivery never calls identity.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    owner_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    target_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    is_blocked = models.BooleanField(
        default=False,
    )
    ghost_until = models.DateTimeField(
        null=True,
        blank=True,
    )

    ghost_permanent = models.BooleanField(
        default=False,
    )

    ghost_duration_option = models.CharField(
        max_length=20,
        blank=True,
        default="",
    )

    policy_version = models.PositiveIntegerField(
        default=1,
    )

    source_updated_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    synced_at = models.DateTimeField(
        auto_now=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        db_table = "messenger_contact_delivery_policies"
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "owner_user_id",
                    "target_user_id",
                ],
                name="uniq_contact_policy_owner_target",
            ),
            models.CheckConstraint(
                condition=~Q(owner_user_id=models.F("target_user_id")),
                name="ck_contact_policy_not_self",
            ),
        ]
        indexes = [
            models.Index(
                fields=[
                    "owner_user_id",
                    "target_user_id",
                    "is_blocked",
                ],
                name="contact_policy_lookup_idx",
            ),
        ]

    def clean(self) -> None:
        super().clean()

        self.owner_user_id = str(self.owner_user_id).strip()
        self.target_user_id = str(self.target_user_id).strip()
        
        errors = {}
        allowed_ghost_options = {
            "",
            "1h",
            "6h",
            "12h",
            "24h",
            "permanent",
        }

        self.ghost_duration_option = str(
            self.ghost_duration_option or ""
        ).strip()



        if self.ghost_duration_option not in allowed_ghost_options:
            errors["ghost_duration_option"] = (
                "Ghost duration option is invalid."
            )
        if not self.owner_user_id:
            errors["owner_user_id"] = "Owner user ID is required."

        if not self.target_user_id:
            errors["target_user_id"] = "Target user ID is required."

        if (
            self.owner_user_id
            and self.target_user_id
            and self.owner_user_id == self.target_user_id
        ):
            errors["target_user_id"] = (
                "Target user ID must be different from owner user ID."
            )

        if self.policy_version < 1:
            errors["policy_version"] = (
                "Policy version must be at least 1."
            )

        if errors:
            raise ValidationError(errors)



class DirectMessageReceiptDecision(models.Model):
    """
    Per-message receipt policy decision.

    This is created at message-send time. If a user was ghosting the sender
    at that moment, delivered/read receipts stay suppressed forever for that
    message, even after the ghost duration expires.
    """

    class PolicyReason(models.TextChoices):
        NORMAL = "normal", "Normal"
        BLOCKED = "blocked", "Blocked"
        GHOST = "ghost", "Ghost"

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    message = models.OneToOneField(
        Message,
        on_delete=models.CASCADE,
        related_name="receipt_decision",
    )

    sender_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    recipient_user_id = models.CharField(
        max_length=EXTERNAL_USER_ID_MAX_LENGTH,
    )

    suppress_delivered_receipt = models.BooleanField(
        default=False,
    )

    suppress_read_receipt = models.BooleanField(
        default=False,
    )

    policy_reason = models.CharField(
        max_length=20,
        choices=PolicyReason.choices,
        default=PolicyReason.NORMAL,
    )

    policy_version = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        db_table = "messenger_direct_message_receipt_decisions"
        indexes = [
            models.Index(
                fields=[
                    "message",
                    "recipient_user_id",
                ],
                name="dm_rec_dec_msg_user_idx",
            ),
            models.Index(
                fields=[
                    "recipient_user_id",
                    "sender_user_id",
                    "policy_reason",
                ],
                name="dm_receipt_decision_pair_idx",
            ),
        ]

    def clean(self) -> None:
        super().clean()

        self.sender_user_id = str(self.sender_user_id).strip()
        self.recipient_user_id = str(self.recipient_user_id).strip()

        errors = {}

        if not self.sender_user_id:
            errors["sender_user_id"] = "Sender user ID is required."

        if not self.recipient_user_id:
            errors["recipient_user_id"] = "Recipient user ID is required."

        if (
            self.sender_user_id
            and self.recipient_user_id
            and self.sender_user_id == self.recipient_user_id
        ):
            errors["recipient_user_id"] = (
                "Recipient user ID must be different from sender user ID."
            )

        if self.policy_version is not None and self.policy_version < 1:
            errors["policy_version"] = (
                "Policy version must be at least 1."
            )

        if errors:
            raise ValidationError(errors)