# Generated by Django 5.2.15 on 2026-06-27 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('avatar_storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('created_by_user_id', models.CharField(max_length=128)),
                ('max_members', models.PositiveSmallIntegerField(default=100)),
                ('join_history_visible', models.BooleanField(default=False)),
                ('only_admins_can_send', models.BooleanField(default=False)),
                ('only_admins_can_edit_info', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='rooms.room')),
            ],
            options={
                'db_table': 'messenger_group_profiles',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by_user_id', '-created_at'], name='group_profile_creator_idx')],
            },
        ),
    ]
