# Generated by Django 5.2.15 on 2026-06-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2ee_devices', '0002_recoverybundle'),
        ('group_chat', '0005_group_sender_key_distribution'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupsenderkeydistribution',
            name='unique_sender_key_recipient_device',
        ),
        migrations.RemoveConstraint(
            model_name='groupsenderkeydistribution',
            name='group_sender_distribution_version_gte_1',
        ),
        migrations.RenameIndex(
            model_name='groupsenderkeydistribution',
            new_name='gskd_key_status_idx',
            old_name='group_sender_dist_key_status_idx',
        ),
        migrations.AddConstraint(
            model_name='groupsenderkeydistribution',
            constraint=models.UniqueConstraint(fields=('sender_key', 'recipient_device'), name='uniq_gskd_key_device'),
        ),
        migrations.AddConstraint(
            model_name='groupsenderkeydistribution',
            constraint=models.CheckConstraint(condition=models.Q(('distribution_version__gte', 1)), name='gskd_version_gte_1'),
        ),
    ]
