# Generated by Django 5.2.15 on 2026-06-26 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=20)),
                ('registration_id', models.PositiveIntegerField()),
                ('identity_key_public', models.TextField()),
                ('signed_prekey_id', models.PositiveIntegerField()),
                ('signed_prekey_public', models.TextField()),
                ('signed_prekey_signature', models.TextField()),
                ('key_algorithm', models.CharField(default='curve25519', max_length=50)),
                ('key_bundle_version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messenger_devices',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='device_user_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='OneTimePreKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.PositiveIntegerField()),
                ('public_key', models.TextField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_prekeys', to='e2ee_devices.device')),
            ],
            options={
                'db_table': 'messenger_one_time_prekeys',
                'ordering': ['key_id'],
                'indexes': [models.Index(fields=['device', 'is_claimed', 'key_id'], name='prekey_available_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'key_id'), name='unique_device_prekey_id'), models.CheckConstraint(condition=models.Q(models.Q(('claimed_at__isnull', True), ('is_claimed', False)), models.Q(('claimed_at__isnull', False), ('is_claimed', True)), _connector='OR'), name='prekey_claim_state_valid')],
            },
        ),
    ]
