# Generated by Django 5.2.15 on 2026-06-26 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2ee_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=128, unique=True)),
                ('recovery_public_key', models.TextField()),
                ('encrypted_recovery_private_key', models.TextField()),
                ('encryption_metadata', models.JSONField(default=dict)),
                ('recovery_version', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messenger_recovery_bundles',
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='recovery_user_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('recovery_version__gte', 1)), name='recovery_version_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('disabled_at__isnull', True), ('is_active', True)), models.Q(('disabled_at__isnull', False), ('is_active', False)), _connector='OR'), name='recovery_active_state_valid')],
            },
        ),
    ]
