# Generated by Django 5.2.15 on 2026-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2ee_devices', '0002_recoverybundle'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user_id', '-last_seen_at'], name='device_user_seen_idx'),
        ),
    ]
