# Generated by Django 5.2.15 on 2026-06-28 16:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e2ee_devices', '0002_recoverybundle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_hash', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_tickets', to='e2ee_devices.device')),
            ],
            options={
                'db_table': 'realtime_tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='rt_ticket_user_created_idx'), models.Index(fields=['device', 'created_at'], name='rt_ticket_device_created_idx'), models.Index(fields=['expires_at'], name='rt_ticket_expires_idx')],
            },
        ),
    ]
