# Generated by Django 5.2.15 on 2026-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_realtimeoutboxevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='realtimeoutboxevent',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='rt_outbox_due_idx'),
        ),
    ]
