# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0003_outbox_due_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimeoutboxevent",
            name="event_key",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="realtimeoutboxevent",
            name="claimed_by",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="realtimeoutboxevent",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="realtimeoutboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("dead", "Dead"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="realtimeoutboxevent",
            index=models.Index(
                fields=["status", "claimed_at"],
                name="rt_outbox_claim_idx",
            ),
        ),
    ]
