# Generated by Django 5.2.15 on 2026-06-26 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_user_id', models.CharField(max_length=128)),
                ('sender_device_id', models.CharField(max_length=128)),
                ('client_message_id', models.UUIDField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('location', 'Location'), ('contact', 'Contact'), ('system', 'System')], default='text', max_length=20)),
                ('encrypted_payload', models.TextField()),
                ('encryption_metadata', models.JSONField(blank=True, default=dict)),
                ('encryption_version', models.PositiveSmallIntegerField(default=1)),
                ('client_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat_messages.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='rooms.room')),
            ],
            options={
                'db_table': 'messenger_messages',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='msg_room_created_idx'), models.Index(fields=['sender_user_id', 'created_at'], name='msg_sender_created_idx'), models.Index(fields=['room', 'message_type', 'created_at'], name='msg_room_type_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender_user_id', 'client_message_id'), name='unique_sender_client_msg')],
            },
        ),
    ]
