# Generated by Django 5.2.15 on 2026-06-26 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('e2ee_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageKeyEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_user_id', models.CharField(max_length=128)),
                ('protocol', models.CharField(choices=[('double_ratchet', 'Double Ratchet'), ('group_sender_key', 'Group Sender Key'), ('device_sync', 'Device Synchronization')], default='double_ratchet', max_length=30)),
                ('session_reference', models.CharField(blank=True, default='', max_length=128)),
                ('wrapped_message_key', models.TextField()),
                ('key_wrap_metadata', models.JSONField(default=dict)),
                ('envelope_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_envelopes', to='chat_messages.message')),
                ('recipient_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_key_envelopes', to='e2ee_devices.device')),
            ],
            options={
                'db_table': 'messenger_message_key_envelopes',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['message', 'recipient_user_id'], name='envelope_message_user_idx'), models.Index(fields=['recipient_device', 'created_at'], name='envelope_device_time_idx'), models.Index(fields=['recipient_user_id', 'created_at'], name='envelope_user_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'recipient_device'), name='unique_message_device_envelope')],
            },
        ),
    ]
