# Generated by Django 5.2.15 on 2026-06-26 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_messagekeyenvelope'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecoveryEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovery_owner_user_id', models.CharField(max_length=128)),
                ('recovery_key_version', models.PositiveSmallIntegerField()),
                ('wrapped_message_key', models.TextField()),
                ('key_wrap_metadata', models.JSONField(default=dict)),
                ('envelope_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_envelopes', to='chat_messages.message')),
            ],
            options={
                'db_table': 'messenger_message_recovery_envelopes',
                'indexes': [models.Index(fields=['recovery_owner_user_id', '-created_at'], name='recovery_owner_time_idx'), models.Index(fields=['message', 'recovery_owner_user_id'], name='recovery_message_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'recovery_owner_user_id'), name='unique_message_recovery_owner'), models.CheckConstraint(condition=models.Q(('recovery_key_version__gte', 1)), name='recovery_key_version_gte_1'), models.CheckConstraint(condition=models.Q(('envelope_version__gte', 1)), name='recovery_envelope_version_gte_1')],
            },
        ),
    ]
