# Generated by Django 5.2.15 on 2026-07-01 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0008_secure_attachment_hardening'),
        ('rooms', '0002_roommember_group_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectContactState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_user_id', models.CharField(max_length=128)),
                ('contact_user_id', models.CharField(max_length=128)),
                ('identity_contact_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_saved', models.BooleanField(default=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_contact_states', to='rooms.room')),
            ],
            options={
                'db_table': 'messenger_direct_contact_states',
                'indexes': [models.Index(fields=['owner_user_id', 'contact_user_id', 'is_saved'], name='direct_contact_send_lookup_idx'), models.Index(fields=['room', 'owner_user_id'], name='direct_contact_room_owner_idx'), models.Index(fields=['owner_user_id', 'identity_contact_id'], name='direct_contact_identity_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner_user_id', 'contact_user_id'), name='uniq_direct_contact_state_owner_contact'), models.CheckConstraint(condition=models.Q(('owner_user_id', models.F('contact_user_id')), _negated=True), name='ck_direct_contact_state_not_self')],
            },
        ),
    ]
