# Generated by Django 5.2.15 on 2026-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_hot_path_membership_indexes"),
        ("chat_messages", "0009_directcontactstate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at', '-id'], name='msg_room_newest_idx'),
        ),
    ]
