"""remove stored cloudinary url

Revision ID: 6da61ddeca45
Revises: bf4e0d39c265
Create Date: 2026-06-22 14:20:15.501014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6da61ddeca45"
down_revision = "bf4e0d39c265"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile_pictures", schema=None) as batch_op:
        batch_op.drop_column("secure_url")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile_pictures", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "secure_url",
                sa.VARCHAR(length=500),
                nullable=False,
                server_default="",
            )
        )

    # ### end Alembic commands ###
