"""create profile resources

Revision ID: bf4e0d39c265
Revises: 8b2b0dd6df81
Create Date: 2026-06-22 13:48:54.761446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4e0d39c265'
down_revision = '8b2b0dd6df81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.String(length=150), nullable=False),
    sa.Column('address_line_2', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_addresses', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_profile_addresses_user_id'),
            ['user_id'],
            unique=True,
        )

    op.create_table('profile_basics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_basics', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_profile_basics_user_id'),
            ['user_id'],
            unique=True,
        )

    op.create_table('profile_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_events', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_profile_events_user_id'),
            ['user_id'],
            unique=False,
        )

    op.create_table('profile_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('secure_url', sa.String(length=500), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=True),
    sa.Column('image_format', sa.String(length=20), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('profile_pictures', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_profile_pictures_user_id'),
            ['user_id'],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_pictures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_pictures_user_id'))

    op.drop_table('profile_pictures')
    with op.batch_alter_table('profile_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_events_user_id'))

    op.drop_table('profile_events')
    with op.batch_alter_table('profile_basics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_basics_user_id'))

    op.drop_table('profile_basics')
    with op.batch_alter_table('profile_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_addresses_user_id'))

    op.drop_table('profile_addresses')
    # ### end Alembic commands ###
