"""Stable constants for group-chat implementation phases.

Keep protocol-visible and authorization strings centralized here so later
services, serializers, and tests do not scatter literal values.
"""

ROOM_TYPE_GROUP = "group"

GROUP_ROLE_OWNER = "owner"
GROUP_ROLE_ADMIN = "admin"
GROUP_ROLE_MEMBER = "member"
GROUP_ROLES = (
    GROUP_ROLE_OWNER,
    GROUP_ROLE_ADMIN,
    GROUP_ROLE_MEMBER,
)

DEFAULT_GROUP_MEMBER_LIMIT = 100
MAX_GROUP_MEMBER_LIMIT = 500

EPOCH_ROTATION_REASON_INITIAL = "initial"
EPOCH_ROTATION_REASON_MEMBER_ADDED = "member_added"
EPOCH_ROTATION_REASON_MEMBER_REMOVED = "member_removed"
EPOCH_ROTATION_REASON_MEMBER_LEFT = "member_left"
EPOCH_ROTATION_REASON_MEMBER_BANNED = "member_banned"
EPOCH_ROTATION_REASON_MANUAL = "manual"
EPOCH_ROTATION_REASON_SECURITY_INCIDENT = "security_incident"
EPOCH_ROTATION_REASONS = (
    EPOCH_ROTATION_REASON_INITIAL,
    EPOCH_ROTATION_REASON_MEMBER_ADDED,
    EPOCH_ROTATION_REASON_MEMBER_REMOVED,
    EPOCH_ROTATION_REASON_MEMBER_LEFT,
    EPOCH_ROTATION_REASON_MEMBER_BANNED,
    EPOCH_ROTATION_REASON_MANUAL,
    EPOCH_ROTATION_REASON_SECURITY_INCIDENT,
)

GROUP_SENDER_KEY_ALGORITHM = "group-sender-key-v1"
GROUP_SENDER_KEY_SIGNING_ALGORITHM = "ed25519"
GROUP_SENDER_KEY_VERSION = 1

GROUP_SENDER_KEY_DISTRIBUTION_VERSION = 1
GROUP_SENDER_KEY_DISTRIBUTION_STATUS_STORED = "stored"
GROUP_SENDER_KEY_DISTRIBUTION_STATUS_ACKNOWLEDGED = "acknowledged"
GROUP_SENDER_KEY_DISTRIBUTION_STATUSES = (
    GROUP_SENDER_KEY_DISTRIBUTION_STATUS_STORED,
    GROUP_SENDER_KEY_DISTRIBUTION_STATUS_ACKNOWLEDGED,
)

GROUP_AUDIT_GROUP_CREATED = "group_created"
GROUP_AUDIT_GROUP_UPDATED = "group_updated"
GROUP_AUDIT_MEMBERS_ADDED = "members_added"
GROUP_AUDIT_MEMBER_REMOVED = "member_removed"
GROUP_AUDIT_MEMBER_LEFT = "member_left"
GROUP_AUDIT_ROLE_CHANGED = "role_changed"
GROUP_AUDIT_OWNERSHIP_TRANSFERRED = "ownership_transferred"
GROUP_AUDIT_MEMBER_BANNED = "member_banned"
GROUP_AUDIT_MEMBER_UNBANNED = "member_unbanned"
GROUP_AUDIT_EPOCH_ROTATED = "epoch_rotated"
GROUP_AUDIT_SENDER_KEY_REGISTERED = "sender_key_registered"
GROUP_AUDIT_SENDER_KEY_REVOKED = "sender_key_revoked"
GROUP_AUDIT_SENDER_KEY_DISTRIBUTED = "sender_key_distributed"
GROUP_AUDIT_SENDER_KEY_DISTRIBUTION_ACKED = "sender_key_distribution_acked"

GROUP_SECURITY_TRANSITION_REASON_MEMBER_ADDED = "member_added"
GROUP_SECURITY_TRANSITION_REASON_MEMBER_REMOVED = "member_removed"
GROUP_SECURITY_TRANSITION_REASON_MEMBER_LEFT = "member_left"
GROUP_SECURITY_TRANSITION_REASON_MEMBER_BANNED = "member_banned"
GROUP_SECURITY_TRANSITION_REASON_MEMBER_UNBANNED = "member_unbanned"
GROUP_SECURITY_TRANSITION_REASON_MEMBER_REACTIVATED = "member_reactivated"
GROUP_SECURITY_TRANSITION_REASON_DEVICE_ADDED = "device_added"
GROUP_SECURITY_TRANSITION_REASON_DEVICE_DEACTIVATED = "device_deactivated"
GROUP_SECURITY_TRANSITION_REASON_MANUAL_SECURITY_ROTATION = (
    "manual_security_rotation"
)

GROUP_SECURITY_TRANSITION_REASONS = (
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_ADDED,
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_REMOVED,
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_LEFT,
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_BANNED,
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_UNBANNED,
    GROUP_SECURITY_TRANSITION_REASON_MEMBER_REACTIVATED,
    GROUP_SECURITY_TRANSITION_REASON_DEVICE_ADDED,
    GROUP_SECURITY_TRANSITION_REASON_DEVICE_DEACTIVATED,
    GROUP_SECURITY_TRANSITION_REASON_MANUAL_SECURITY_ROTATION,
)

GROUP_SECURITY_TRANSITION_STATUS_PENDING = "pending"
GROUP_SECURITY_TRANSITION_STATUS_APPLIED = "applied"
GROUP_SECURITY_TRANSITION_STATUS_FAILED = "failed"

GROUP_SECURITY_TRANSITION_STATUSES = (
    GROUP_SECURITY_TRANSITION_STATUS_PENDING,
    GROUP_SECURITY_TRANSITION_STATUS_APPLIED,
    GROUP_SECURITY_TRANSITION_STATUS_FAILED,
)

GROUP_AUDIT_SECURITY_TRANSITION_CREATED = "security_transition_created"
GROUP_AUDIT_SECURITY_TRANSITION_APPLIED = "security_transition_applied"
GROUP_AUDIT_SECURITY_TRANSITION_FAILED = "security_transition_failed"

GROUP_AUDIT_EVENT_TYPES = (
    GROUP_AUDIT_GROUP_CREATED,
    GROUP_AUDIT_GROUP_UPDATED,
    GROUP_AUDIT_MEMBERS_ADDED,
    GROUP_AUDIT_MEMBER_REMOVED,
    GROUP_AUDIT_MEMBER_LEFT,
    GROUP_AUDIT_ROLE_CHANGED,
    GROUP_AUDIT_OWNERSHIP_TRANSFERRED,
    GROUP_AUDIT_MEMBER_BANNED,
    GROUP_AUDIT_MEMBER_UNBANNED,
    GROUP_AUDIT_EPOCH_ROTATED,
    GROUP_AUDIT_SENDER_KEY_REGISTERED,
    GROUP_AUDIT_SENDER_KEY_REVOKED,
    GROUP_AUDIT_SENDER_KEY_DISTRIBUTED,
    GROUP_AUDIT_SENDER_KEY_DISTRIBUTION_ACKED,
    GROUP_AUDIT_SECURITY_TRANSITION_CREATED,
    GROUP_AUDIT_SECURITY_TRANSITION_APPLIED,
    GROUP_AUDIT_SECURITY_TRANSITION_FAILED,
)