#!/bin/sh
set -eu

case "${MYSQL_IDENTITY_DATABASE:-}" in (*[!A-Za-z0-9_]*) echo "Invalid MYSQL_IDENTITY_DATABASE" >&2; exit 2;; esac
case "${MYSQL_MESSENGER_DATABASE:-}" in (*[!A-Za-z0-9_]*) echo "Invalid MYSQL_MESSENGER_DATABASE" >&2; exit 2;; esac
case "${MYSQL_APP_USER:-}" in (*[!A-Za-z0-9_]*) echo "Invalid MYSQL_APP_USER" >&2; exit 2;; esac

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MYSQL_IDENTITY_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS \`${MYSQL_MESSENGER_DATABASE}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
ALTER USER '${MYSQL_APP_USER}'@'%' IDENTIFIED BY '${MYSQL_APP_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MYSQL_IDENTITY_DATABASE}\`.* TO '${MYSQL_APP_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${MYSQL_MESSENGER_DATABASE}\`.* TO '${MYSQL_APP_USER}'@'%';
FLUSH PRIVILEGES;
SQL
